add command arguments

diff --git a/optionsmerge b/optionsmerge
--- a/optionsmerge
+++ b/optionsmerge
@@ -3,96 +3,76 @@
 # THE IDEA:
 #
 # global : the global file containing default settings
-# local  : the local options file for a game instance
+# local	: the local options file for a game instance
 # synced : the list of synced options and their most recent synced value. the value here is used to determine if the setting was changed
 #
 # modes:
-#     respect (default): respect locally changed options. if a synced option is changed locally, it will not be overwritten
-#     overwrite: overwrites all options the SYNCED file regardless of if it's been changed locally
+#		 respect (default): respect locally changed options. if a synced option is changed locally, it will not be overwritten
+#		 overwrite: overwrites all options the SYNCED file regardless of if it's been changed locally
 #
 # setup: create a file called sync.txt. this file contains the list of settings (and their initial values) that will be synced between the settings files.
-#        this file should contain a subset of options from LOCAL exactly as they are written (`<option>:<value>`).
+#				this file should contain a subset of options from LOCAL exactly as they are written (`<option>:<value>`).
 #
 # on game start: read GLOAL, LOCAL, and SYNCED. recreate LOCAL: if synced == local != global: replace local with global, update synced.txt
 
-GLOBAL=./global.txt
-LOCAL=./local.txt
-SYNCED=./sync.txt
+GLOBAL=
+LOCAL=
+SYNCED=
 
 MODE=respect
+YES=0
 
 changed() {
-  comm -i13 <(sort "$1") <(sort "$2")
+	comm -i13 <(sort "$1") <(sort "$2")
 }
 
 declare -A global_options local_options synced_options _seen_options changed_options
 declare -a options_order
 
 load_file() {
-  local file="$1"
-  local -n map="$2"
+	local file="$1"
+	local -n map="$2"
 
-  while IFS= read line ; do
-    IFS=: read -r key val <<< "$line"
-    map["$key"]="$val"
+	while IFS= read line ; do
+		IFS=: read -r key val <<< "$line"
+		map["$key"]="$val"
 
-    if [[ ! -v _seen_options["$key"] ]] ; then
-      options_order+=("$key")
-      _seen_options["$key"]=1
-    fi
+		if [[ ! -v _seen_options["$key"] ]] ; then
+			options_order+=("$key")
+			_seen_options["$key"]=1
+		fi
 
-  done < "$file"
+	done < "$file"
 }
 
 printmap() {
-  local -n map="$1"
+	local -n map="$1"
 
-  local -a sorted_keys=("${options_order[@]}" "${!map[@]}")
+	local -a sorted_keys=("${options_order[@]}" "${!map[@]}")
 
-  sorted_keys=($(IFS=$'\n' ; echo "${sorted_keys[*]}" | command cat -n | sort -uk2 | sort -nk1 | cut -f2-))
+	sorted_keys=($(IFS=$'\n' ; echo "${sorted_keys[*]}" | command cat -n | sort -uk2 | sort -nk1 | cut -f2-))
 
-  for key in "${sorted_keys[@]}" ; do
-    [[ -v map["$key"] ]] && printf '%s\n%s\n' "$key" "${map["$key"]}"
-  done | paste -d' ' - - | column -t
+	for key in "${sorted_keys[@]}" ; do
+		[[ -v map["$key"] ]] && printf '%s\n%s\n' "$key" "${map["$key"]}"
+	done | paste -d' ' - - | column -t
 }
 
 formatoptions() {
-  local -n map="$1"
+	local -n map="$1"
 
-  local -a sorted_keys=("${options_order[@]}" "${!map[@]}" "${!changed_options[@]}")
-  sorted_keys=($(IFS=$'\n' ; echo "${sorted_keys[*]}" | command cat -n | sort -uk2 | sort -nk1 | cut -f2-))
+	local -a sorted_keys=("${options_order[@]}" "${!map[@]}" "${!changed_options[@]}")
+	sorted_keys=($(IFS=$'\n' ; echo "${sorted_keys[*]}" | command cat -n | sort -uk2 | sort -nk1 | cut -f2-))
 
-  local optionstxt=""
+	local optionstxt=""
 
-  for key in "${sorted_keys[@]}" ; do
-    if [[ -v map["$key"] ]] ; then
-      optionstxt+="${key}:${map["$key"]}"
-      optionstxt+=$'\n'
-    fi
-  done
+	for key in "${sorted_keys[@]}" ; do
+		if [[ -v map["$key"] ]] ; then
+			optionstxt+="${key}:${map["$key"]}"
+			optionstxt+=$'\n'
+		fi
+	done
 
-  echo -n "$optionstxt"
-}
-
-# creates the sync file but DOES NOT CHANGE options.txt
-initcmd() {
-  local mode="$1"
-  local global_file="$2"
-  local sync_file="${3:-./synced-options.txt}"
-
-  case "${mode,,}" in
-    # creates an empty sync file
-    "empty")
-      ;;
-
-    # creates a sync file with every option in synced-options.txt
-    "fullclone" | "full-clone")
-      load_file "$global_file" global_options
-      for key in "${options_order[@]}" ; do
-        synced_options["$key"]=""
-      done
-      ;;
-  esac
+	echo -n "$optionstxt"
 }
 
 # l == s and s == g -> synced
@@ -101,48 +81,129 @@ initcmd() {
 # else -> ambiguous
 
 syncoptions() {
-  for opt in "${!synced_options[@]}" ; do
-    local s="${synced_options["$opt"]}"
-    local l="${local_options["$opt"]}"
-    local g="${global_options["$opt"]}"
+	for opt in "${!synced_options[@]}" ; do
+		local s="${synced_options["$opt"]}"
+		local l="${local_options["$opt"]}"
+		local g="${global_options["$opt"]}"
 
-    if [[ ($MODE == "respect" && $l == $s && $s != $g) || ($MODE == "overwrite" && $l != $g) ]] ; then
-      local_options["$opt"]="$g"
-      changed_options["$opt"]="$g"
-      synced_options["$opt"]="$g"
-    else
-      unset synced_options["$opt"]
-    fi
-  done
+		if [[ ($MODE == "respect" && $l == $s && $s != $g) || ($MODE == "overwrite" && $l != $g) ]] ; then
+			local_options["$opt"]="$g"
+			changed_options["$opt"]="$g"
+			synced_options["$opt"]="$g"
+		else
+			unset synced_options["$opt"]
+		fi
+	done
 }
 
 do-sync() {
-  load_file "$GLOBAL" global_options
-  load_file "$LOCAL" local_options
-  load_file "$SYNCED" synced_options
-  load_file "$SYNCED" changed_options
+	load_file "$GLOBAL" global_options
+	load_file "$LOCAL" local_options
+	load_file "$SYNCED" synced_options
+	load_file "$SYNCED" changed_options
 
-  syncoptions
+	syncoptions
 
-  if [[ ${#synced_options[@]} > 0 ]] ; then
-    echo 'The following changes settings will be updated:'
-    printmap synced_options
+	if [[ ${#synced_options[@]} -gt 0 ]] ; then
+		echo 'The following changes settings will be updated:'
+		printmap synced_options
 
-    read -p 'Apply changes? [y/n] ' yn
-    if [[ ! "$yn" =~ [Yy] ]] ; then
-      return 0
-    fi
+		if [[ $YES != 1 ]] ; then
+			read -p 'Apply changes? [y/n] ' yn
+			if [[ ! "$yn" =~ [Yy] ]] ; then
+				return 0
+			fi
+		fi
 
-    echo 'updating local options'
-    cp "$LOCAL" "$LOCAL.bak"
-    formatoptions local_options | tee "$LOCAL"
+		err
+		err 'writing local options'
+		cp "$LOCAL" "$LOCAL.bak"
+		formatoptions local_options | tee "$LOCAL" >&2
 
-    echo 'updating sync file'
-    cp "$SYNCED" "$SYNCED.bak"
-    formatoptions changed_options | tee "$SYNCED"
-  else
-    echo 'options.txt is up to date'
-  fi
+		err
+		err 'writing sync file'
+		cp "$SYNCED" "$SYNCED.bak"
+		formatoptions changed_options | tee "$SYNCED" >&2
+	else
+		err "$(basename "$LOCAL") is up to date"
+	fi
 }
 
-do-sync
+err() {
+	echo $@ >&2
+}
+
+while getopts ":g:l:s:m:yh" opt ; do
+	case "$opt" in
+		g)
+			GLOBAL="$OPTARG"
+			;;
+
+		l)
+			LOCAL="$OPTARG"
+			;;
+
+		s)
+			SYNCED="$OPTARG"
+			;;
+
+		m)
+			if [[ ! "${OPTARG,,}" =~ ^(respect|overwrite) ]] ; then
+				err "-m [mode] : mode must be one of: respect, overwrite"
+				exit 1
+			fi
+			MODE="${OPTARG,,}"
+			;;
+
+		y)
+			YES=1
+			;;
+
+		:)
+			err "-$OPTARG requires an argument"
+			exit 1
+			;;
+
+		\?)
+			err "invalid option: -$OPTARG"
+			exit 1
+			;;
+	esac
+done
+
+shift $((OPTIND-1))
+
+cmd="$1"
+shift
+
+opts=("GLOBAL" "LOCAL" "SYNCED")
+for arg in ${opts[@]} ; do
+	if [[ -z "${!arg}" ]] ; then
+		err "missing argument for $arg"
+		cmd=help
+	fi
+done
+
+case "$cmd" in
+	sync)
+		do-sync
+		;;
+
+	"help" | *)
+		cat <<- EOH
+		Minecraft options.txt sync
+
+		Usage: optionsync [options] <sync|help>
+
+		Options:
+		    -g <file>                 global options.txt file ($GLOBAL)
+		    -l <file>                 local options.txt file ($LOCAL)
+		    -s <file>                 sync file ($SYNCED)
+		    -m <respect|overwrite>    sync mode ($MODE)
+		    -y                        bypass confirmation ($YES)
+		EOH
+		;;
+
+	esac
+
+# vim: noet
